include:
    - project: "GNOME/citemplates"
      file: "flatpak/flatpak_ci_initiative.yml"
    - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/f9171e21724bc4e2abeabad5f2d7e2e5cc10cbe3/templates/fedora.yml'

stages:
    - lint
    - prepare
    - build
    - deploy

variables:
    # When branching a stable release, change 'main'
    # to the release number/branch to ensure that
    # a new image will be created, tailored for the
    # stable branch.
    # Could probably also switch away from rawhide,
    # to stable fedora branch as well.
    FDO_DISTRIBUTION_TAG: '2024-01-11.1-main'
    FDO_DISTRIBUTION_VERSION: rawhide

editorconfig:
    stage: lint
    image: alpine:edge
    script:
        - apk add editorconfig-checker
        - ec --disable-indentation --exclude '^.git/|cut-n-paste'

build.container.fedora:
    extends: '.fdo.container-build@fedora'
    stage: prepare
    variables:
        # no need to pull the whole tree for rebuilding the image
        GIT_STRATEGY: none
        # Expiry sets fdo.expires on the image
        FDO_EXPIRES_AFTER: 8w
        FDO_DISTRIBUTION_PACKAGES: >-
            meson
            appstream
            cairo-devel
            dbus-devel
            desktop-file-utils
            djvulibre-devel
            exempi-devel
            gi-docgen
            glib2-devel
            gnome-desktop4-devel
            gobject-introspection-devel
            gsettings-desktop-schemas-devel
            gtk4-devel
            itstool
            libadwaita-devel
            libarchive-devel
            libgxps-devel
            libsecret-devel
            libspectre-devel
            libtiff-devel
            nautilus-devel
            poppler-glib-devel
            texlive-lib-devel
            yelp-tools
            zlib-devel

.run-meson:
    stage: build
    extends: '.fdo.distribution-image@fedora'
    artifacts:
        when: on_failure
        paths:
            - _build/meson-logs/meson-log.txt
        expire_in: 2 days

meson:
    extends: '.run-meson'
    script:
        - meson setup _build
        - meson compile -C _build

meson-internal-synctex:
    extends: '.run-meson'
    script:
        - meson setup -Dinternal_synctex=true _build
        - meson compile -C _build

flatpak:
    extends: .flatpak
    stage: build
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Evince.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "evince"
        APP_ID: "org.gnome.Evince"
        BUNDLE: "org.gnome.Evince.flatpak"

pages:
    image: registry.gitlab.gnome.org/gnome/evince/x86_64-ubuntu:gtk4v2
    stage: deploy
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == "GNOME"
    script:
        - meson setup _build
        - ninja -C _build
        - mkdir public
        - mv _build/help/reference/libdocument/libevdocument public/document/
        - mv _build/help/reference/libview/libevview public/view/
    artifacts:
        paths:
            - public/
        expire_in: 2 days
