// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// from ../pps-girs
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

#[doc(alias = "pps_filter_css_chars")]
pub fn filter_css_chars(str: &str) -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_full(ffi::pps_filter_css_chars(str.to_glib_none().0)) }
}
