[options]
girs_directories = ["../gir-files", "../ev-girs"]
library = "PapersDocument"
version = "4.0"
min_cfg_version = "4.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
disable_format = false

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gtk",
   "Pango",
]

generate = [
    "PapersDocument.Attachment",
    "PapersDocument.DocumentAttachments",
    "PapersDocument.DocumentLinks",
    "PapersDocument.DocumentInfoFields",
    "PapersDocument.DocumentContainsJS",
    "PapersDocument.DocumentFonts",
    "PapersDocument.DocumentLicense",
    "PapersDocument.DocumentLayers",
    #"PapersDocument.RenderContext",
    "PapersDocument.Selection",
    "PapersDocument.Annotation",
    "PapersDocument.AnnotationType",
    "PapersDocument.Image",
    "PapersDocument.Page",
    #"PapersDocument.BackendPage",
    "PapersDocument.LinkAction",
    "PapersDocument.LinkDest",
    "PapersDocument.Link",
    "PapersDocument.Layer",
    "PapersDocument.Outlines",
    "PapersDocument.TransitionEffect",
    "PapersDocument.SelectionStyle",
    "PapersDocument.TransitionEffectType",
    "PapersDocument.TransitionEffectAlignment",
    "PapersDocument.TransitionEffectDirection",
]

manual = [
    "GdkPixbuf.Pixbuf",
    "GLib.DateTime",
    "Gtk.Widget",
    "Gio.ListModel",
    "Gio.AppLaunchContext",
    "Gio.File",
    "GLib.Error",
]

[[object]]
name = "PapersDocument.Rectangle"
status = "generate"
boxed_inline = true

[[object]]
name = "PapersDocument.DocumentInfo"
status = "generate"
boxed_inline = true

[[object]]
name = "PapersDocument.Document"
status = "generate"
    [[object.function]]
    name = "get_min_page_size"
    manual = true
    [[object.function]]
    name = "get_max_page_size"
    manual = true
    [[object.function]]
    name = "find_page_by_label"
    manual = true
