name: papers
version: git
summary: Document viewer for popular document formats
description: |
  This is a document viewer for the GNOME desktop.
  It supports the following document formats: PDF, PS, EPS, XPS, DjVu, TIFF, DVI (with SyncTeX), and Comic Books archives (CBR, CBT, CBZ, CB7).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  papers:
    interface: dbus
    bus: session
    name: org.gnome.Papers

apps:
  papers:
    command: usr/bin/papers
    extensions: [gnome-3-38]
    plugs:
      - avahi-observe
      - cups-control
      - gsettings
      - home
      - network
      - removable-media
    desktop: usr/share/applications/org.gnome.Papers.desktop
  papers-previewer:
    command: usr/bin/papers-previewer
    plugs:
      - avahi-observe
      - cups-control
      - gsettings
      - home
      - network
    desktop: usr/share/applications/org.gnome.Papers-previewer.desktop
  papers-thumbnailer:
    command: usr/bin/papers-thumbnailer
    plugs:
      - gsettings
      - home

parts:
  papers:
    source: .
    source-type: git
    plugin: meson
    meson-parameters:
       - --prefix=/snap/papers/current/usr
       - -Dnautilus=false
       - -Dgtk_doc=false
       - -Dintrospection=false

    organize:
      snap/papers/current/usr: usr
    build-packages:
      - appstream
      - intltool
      - libarchive-dev
      - libgail-3-dev
      - libgspell-1-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libsecret-1-dev
      - libsm-dev
      - zlib1g-dev
      - libpoppler-glib-dev
      - libspectre-dev
      - libtiff-dev
      - libdjvulibre-dev
      - libkpathsea-dev
      - libgxps-dev
      - autotools-dev
      - gsettings-desktop-schemas-dev
      - dh-apparmor
    prime:
      - "-usr/lib/*.a"
      - "-usr/lib/mozilla"
      - "-usr/lib/pkgconfig"
      - "-usr/lib/systemd"
      - "-usr/lib/papers/4/backends/*.a"
      - "-usr/share/appdata"
  libraries:
    plugin: nil
    stage-packages:
      - libarchive13
      - libpoppler-glib8
      - libpoppler97
      - libnss3
      - libnspr4
    prime:
      - "usr/lib/*/libarchive.so.*"
      - "usr/lib/*/libpoppler-glib.so.*"
      - "usr/lib/*/libpoppler.so.*"
      - "usr/lib/*/libnss3.so"
      - "usr/lib/*/libnssutil3.so"
      - "usr/lib/*/libsmime3.so"
      - "usr/lib/*/libnspr4.so"
      - "usr/lib/*/libplc4.so"
      - "usr/lib/*/libplds4.so"
